# Generated by Django 2.0.5 on 2018-12-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobtitle', models.CharField(default='', max_length=250)),
                ('image', models.ImageField(default='', upload_to='images/')),
                ('summary', models.CharField(default='', max_length=200)),
                ('website', models.URLField(default='', max_length=250)),
            ],
        ),
    ]
