# Generated by Django 2.0.5 on 2018-12-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20181206_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='website',
            field=models.URLField(default='', max_length=250),
        ),
    ]
