# Generated by Django 2.0.5 on 2018-12-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_work_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('jobpublished', 'Jobpublished')], default='draft', max_length=10),
        ),
    ]
