# Generated by Django 2.0.5 on 2018-12-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_auto_20181206_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='gitlink',
            field=models.URLField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='work',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
    ]
